// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrq4G1gFg2WxWN269AGzXEUHldsyrGQk',
    appId: '1:827017233880:web:7ce118158080af056c5ead',
    messagingSenderId: '827017233880',
    projectId: 'iotback',
    authDomain: 'iotback.firebaseapp.com',
    storageBucket: 'iotback.firebasestorage.app',
    measurementId: 'G-NJDN060DJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlvddyJ0n0hp1Ngh0KkfIy3i_pLF7Jd0',
    appId: '1:827017233880:android:e251edbd14aa1f3e6c5ead',
    messagingSenderId: '827017233880',
    projectId: 'iotback',
    storageBucket: 'iotback.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2TyAT8n7sx8p6HzBUJnY6dvapySi4BBU',
    appId: '1:827017233880:ios:a4c060b48da87e586c5ead',
    messagingSenderId: '827017233880',
    projectId: 'iotback',
    storageBucket: 'iotback.firebasestorage.app',
    iosBundleId: 'com.example.deviceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2TyAT8n7sx8p6HzBUJnY6dvapySi4BBU',
    appId: '1:827017233880:ios:a4c060b48da87e586c5ead',
    messagingSenderId: '827017233880',
    projectId: 'iotback',
    storageBucket: 'iotback.firebasestorage.app',
    iosBundleId: 'com.example.deviceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrq4G1gFg2WxWN269AGzXEUHldsyrGQk',
    appId: '1:827017233880:web:9ce37f0f8a63dfab6c5ead',
    messagingSenderId: '827017233880',
    projectId: 'iotback',
    authDomain: 'iotback.firebaseapp.com',
    storageBucket: 'iotback.firebasestorage.app',
    measurementId: 'G-YDK4F0WDBJ',
  );
}
